### ISSUE TITLE
Coderabbit Refactor Suggestion ListItem.css

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#254]
### 🛠️ Refactor Suggestion

**File:** `frontend/src/components/TourComponents/List/ListItem/ListItem.css`

#### General Improvements
- **Accessibility Enhancements:**
  - Ensure the list item is accessible for everyone.
  - Improve keyboard navigation.

- **Responsive Design:**
  - Make the list item more responsive to different screen sizes.

- **Maintainability Enhancements:**
  - Use CSS variables for easier style management.

#### Code Changes

```css
:root {
  --title-font-size: 16px;
  --description-font-size: 14px;
  --id-font-size: 12px;
  --title-margin: 0;
  --description-margin: 2px 0 0 33px;
  --id-margin: 2px 0 0 0;
  --list-item-padding: 10px;
  --list-item-border-radius: 10px;
  --list-item-margin-bottom: 30px;
  --icon-size: 24px;
  --icon-margin: 10px;
}

.list-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--list-item-padding);
  border: 1px solid var(--grey-border);
  border-radius: var(--list-item-border-radius);
  cursor: pointer;
  margin-bottom: var(--list-item-margin-bottom);
  transition: border-color 0.3s ease;
  outline: none;
}

.list-item:hover,
.list-item:focus-visible {
  border: 1px solid var(--main-purple);
  box-shadow: 0 0 0 2px var(--main-purple);
}

@media (max-width: 768px) {
  .list-item {
    flex-direction: column;
    align-items: flex-start;
  }
}

.list-item-icon-container {
  display: flex;
  align-items: center;
  justify-content: center;
  width: var(--icon-size);
  height: var(--icon-size);
  margin-right: var(--icon-margin);
  background-color: var(--main-purple);
  border-radius: 50%;
}

.list-item-icon {
  width: 12px;
  height: 12px;
  color: #FFFFFF;
}

.list-item-info h4 {
  margin: var(--title-margin);
  font-size: var(--title-font-size);
  color: var(--main-text-color);
}

.list-item-info p {
  margin: var(--description-margin);
  font-size: var(--description-font-size);
  color: var(--second-text-color);
}

.item-id {
  margin: var(--id-margin);
  font-size: var(--id-font-size);
  color: var(--second-text-color);
}

.list-item {
  outline: none;
  transition: border-color 0.3s ease, box-shadow 0.3s ease;
}

.list-item:hover,
.list-item:focus-visible,
.list-item:focus {
  border: 1px solid var(--main-purple);
  box-shadow: 0 0 0 2px var(--main-purple);
}

.list-item:focus:not(:focus-visible) {
  outline: none;
  box-shadow: none;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.list-item-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.list-item-actions .MuiIconButton-root {
  color: var(--main-text-color);
  transition: color 0.3s ease, transform 0.2s ease;
}

.list-item-actions .MuiIconButton-root:hover,
.list-item-actions .MuiIconButton-root:focus-visible {
  color: var(--main-purple);
  transform: scale(1.1);
}

.list-item-info {
  display: flex;
  flex-direction: column;
  margin-left: var(--icon-margin);
}

.list-item-header {
  display: flex;
  align-items: center;
}
```

**HTML Example:**

```html
<div class="list-item" tabindex="0" role="button" aria-label="List item: [Item Title]">
  <!-- ... item content ... -->
  <span class="visually-hidden">Click to expand</span>
</div>
```

---
